spring.application.name=api
spring.datasource.url=jdbc:mysql://localhost:3306/vollmed_api
spring.datasource.username=root
spring.datasource.password=OnePiece10@

server.error.include-message=never

api.security.token.secret=${JWT_SECRET:1234578}